# Select the proper tag: refer to https://github.com/SergioGasquez/esp-rs-container
# for more information about tags
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - vadimcn.vscode-lldb
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
ports:
  - port: 9012
    visibility: public
