[env]
ESP_LOGLEVEL="INFO"

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
        "-C", "link-arg=-Tlinkall.x",
        #"-C", "link-arg=-Tdefmt.x",
        "-C", "link-arg=-nostartfiles",
        "-Z", "stack-protector=all",
]

[target.xtensa-esp32-none-elf]
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x

[unstable]
build-std = ["alloc", "core"]
